- dlink-doc/bin/auto.sh
JAR_NAME="./dlink-admin-*.jar"
#java -Djava.ext.dirs=$JAVA_HOME/jre/lib/ext:$JAVA_HOME/jre/lib:./lib -classpath ."/lib/*.jar" -jar dlink-admin-*.jar
SETTING="-Dloader.path=./lib,./plugins -Ddruid.mysql.usePingMethod=false"
tips() {
echo ""
echo "WARNING!!!......Tips, please use command: sh auto.sh [start|stop|restart|status].   For example: sh auto.sh start  "
echo ""
exit 1
}
start() {
pid=`ps -ef | grep $JAR_NAME | grep -v grep | awk '{print $2}'`
if [ -z $pid ]; then
nohup java $SETTING -jar -Xms512M -Xmx2048M -XX:PermSize=512M -XX:MaxPermSize=1024M $JAR_NAME > dlink.log 2>&1 &
pid=`ps -ef | grep $JAR_NAME | grep -v grep | awk '{print $2}'`
echo ""
echo "Service ${JAR_NAME} is starting！pid=${pid}"
echo "........................Start successfully！........................."
else
echo "" …
> #!/bin/bash

- dlink-admin/src/main/java/com/dlink/service/impl/CatalogueServiceImpl.java
- dlink-web/src/components/Studio/StudioTabs/index.tsx
- dlink-web/src/pages/FlinkSqlStudio/SqlExport/model.ts
fix: 
修复任务重命名的bug
add:
增加SQLStudio 的多tab 右键关闭菜单(关闭其他/关闭所有(会将草稿关闭))
> fixbug && add SQLStudio Right Menu

- dlink-admin/src/main/java/com/dlink/service/impl/CatalogueServiceImpl.java
- dlink-web/src/components/Studio/StudioTabs/index.tsx
- dlink-web/src/pages/FlinkSqlStudio/SqlExport/model.ts
> Revert "Revert "fixbug && add SQLStudio Right Menu""

- dlink-client/dlink-client-1.11/pom.xml
- dlink-client/dlink-client-1.12/pom.xml
- dlink-client/dlink-client-1.13/pom.xml
- dlink-client/dlink-client-1.14/pom.xml
- dlink-client/dlink-client-hadoop/pom.xml
- dlink-client/pom.xml
- dlink-core/pom.xml
- pom.xml
fix the dependency problem of different hadoop versions.
> fix the dependency problem of different hadoop versions

- dlink-common/src/main/java/com/dlink/model/Table.java
> 优化FlinkDDL

- dlink-alert/dlink-alert-dingtalk/src/main/java/com/dlink/alert/dingtalk/DingTalkConstants.java
- dlink-alert/dlink-alert-dingtalk/src/main/java/com/dlink/alert/dingtalk/DingTalkSender.java
- dlink-alert/dlink-alert-dingtalk/src/test/java/com/dlink/alert/dingtalk/DingTalkTest.java
- dlink-alert/dlink-alert-wechat/src/main/java/com/dlink/alert/wechat/WeChatSender.java
- dlink-common/src/main/java/com/dlink/model/Table.java
- dlink-web/src/pages/AlertInstance/components/DingTalkForm.tsx
- dlink-web/src/pages/AlertInstance/components/WeChatForm.tsx
fix钉钉告警 @所有人 前端回显问题
优化企微告警: 添加钉钉告警发送类型(markdown & Text )
优化FlinkDDL
> 添加钉钉告警的MarkDown和Text消息类型

- dlink-client/dlink-client-1.11/pom.xml
- dlink-client/dlink-client-1.12/pom.xml
- dlink-client/dlink-client-1.13/pom.xml
- dlink-client/dlink-client-1.14/pom.xml
- dlink-client/dlink-client-base/pom.xml
- dlink-connectors/dlink-connector-jdbc-1.12/pom.xml
- dlink-connectors/dlink-connector-jdbc-1.13/pom.xml
- dlink-extends/dependency-reduced-pom.xml
- dlink-extends/pom.xml
- pom.xml
> easy to modify scala version

- dlink-admin/pom.xml
- dlink-web/config/config.dev.ts
- dlink-web/config/config.ts
- dlink-web/package.json
- dlink-web/src/pages/AlertGroup/components/AlertGroupForm.tsx
> 前端优化 pom优化

- dlink-core/src/main/java/com/dlink/api/FlinkAPI.java
- dlink-core/src/main/java/com/dlink/constant/FlinkRestAPIConstant.java
- dlink-core/src/test/java/com/dlink/core/FlinkRestAPITest.java
获取Flink JobManager/TaskManagers相关信息
> 获取Flink JobManager/TaskManagers相关信息

- dlink-web/src/pages/DataBase/components/DataBaseForm.tsx
> 优化hive数据源链接配置

- dlink-core/src/main/java/com/dlink/explainer/Explainer.java
> 修复血缘只能;后问题

- dlink-metadata/dlink-metadata-base/src/main/java/com/dlink/metadata/convert/ITypeConvert.java
- dlink-metadata/dlink-metadata-hive/pom.xml
- dlink-metadata/dlink-metadata-hive/src/main/java/com/dlink/metadata/driver/HiveDriver.java
- dlink-metadata/dlink-metadata-hive/src/test/java/com/dlink/metadata/HiveTest.java
*Fix issues related to Hive JDBC .*
- *Fix bug of querying multiple SQL In Hive JDBC model*  
- *Fix the resultSet data type conversion of Hive JDBC query results*
- *Added metadata-hive  tests for   MultipleSQLTest.*
> [Fix-224] [metadata-hive]  Fix HiveJDBC  Multiple SQL Query

- style/checkstyle.xml
> [Feature-223][style] add checkstyle

- dlink-core/src/main/java/com/dlink/job/JobManager.java
- dlink-gateway/src/main/java/com/dlink/gateway/yarn/YarnApplicationGateway.java
> [fix-234][core] Fix to flink jar cannot be monitored

- pom.xml
> [fix-222][pom] fix root pom mybatis-plus-boot-starter to latest

- dlink-admin/src/main/java/com/dlink/controller/APIController.java
- dlink-admin/src/main/java/com/dlink/dto/APISavePointTaskDTO.java
- dlink-admin/src/main/resources/json/openapi_savepointtask.json
> [Feature-242][admin] add open api named savepointTask

- dlink-admin/src/main/java/com/dlink/db/config/MybatisPlusConfigure.java
- dlink-admin/src/main/java/com/dlink/db/model/SuperEntity.java
> [Fix-222][root]Fix to mybatis-plus-boot-starter bug

- dlink-alert/dlink-alert-wechat/src/main/java/com/dlink/alert/wechat/WeChatConstants.java
- dlink-alert/dlink-alert-wechat/src/main/java/com/dlink/alert/wechat/WeChatSender.java
- dlink-alert/dlink-alert-wechat/src/main/java/com/dlink/alert/wechat/WeChatType.java
- dlink-alert/dlink-alert-wechat/src/test/java/com/dlink/alert/wechat/WeChatSenderTest.java
- dlink-web/src/pages/AlertInstance/components/WeChatForm.tsx
*Add WeChat WebHook AlertType*
- *Add WeChat WebHook AlertType*
- *Change WeChatForm.tsx add Wechat WebHook Type*
- *Added alert-wechat Tests  `testChatMarkDownMsg `   `testChatTextMsg`   for WeChatSenderTest  .*
>  [Feature-211][alert-wechat]  Add WeChat WebHook AlertType

- docs/zh-CN/_sidebar.md
- docs/zh-CN/api/openapi.md
- docs/zh-CN/extend/integrate.md
- docs/zh-CN/quick_start/build.md
> [Feature-226][docs] add openAPI and integration documment

- docs/zh-CN/_sidebar.md
- docs/zh-CN/dinky_overview.md
add dinky_overview and Modifty _sidebar
*(or)*
(or)
> [Bug-248] [docs] add dinky_overview and Modifty _sidebar document

- dlink-web/src/pages/AlertInstance/components/DingTalkForm.tsx
- dlink-web/src/pages/AlertInstance/components/WeChatForm.tsx
> [Fix-211][web]Fix to form linkage

- docs/zh-CN/administrator-guide/Studio/job_manage.md
- docs/zh-CN/extend/datasource.md
Modify data source extension
add datasource.md
*(or)*
(or)
> [Fix-257] [docs] Modify data source extension

- dlink-web/src/pages/AlertInstance/components/WeChatForm.tsx
- dlink-web/src/pages/AlertInstance/function.ts
> [Fix-211][web]Fix to create form linkage

- .github/ISSUE_TEMPLATE/document-request.yml
> [Document][docs] Add document request template

- dlink-web/src/components/Studio/StudioMenu/index.tsx
Add a button to exit full screen
> [Fix-192][web] Add a button to exit full screen

- docs/zh-CN/extend/datasource.md
Modifty datasource description
Modifty datasource.md
> [Fix-273] [docs] Modifty datasource document 

- dlink-gateway/src/main/java/com/dlink/gateway/yarn/YarnGateway.java
> [Fix-108][gateway] Fix to cancel per-job bug

- .github/ISSUE_TEMPLATE/optimization-request.yml
> [Feature][root] Add optimization issue template

- .github/ISSUE_TEMPLATE/optimization-request.yml
> [Fix][root] Fix to optimization issue template

- .github/ISSUE_TEMPLATE/optimization-request.yml
- dlink-admin/src/main/java/com/dlink/dto/StudioCADTO.java
- dlink-admin/src/main/java/com/dlink/service/impl/JobInstanceServiceImpl.java
- dlink-admin/src/main/java/com/dlink/service/impl/StudioServiceImpl.java
- dlink-core/src/main/java/com/dlink/explainer/Explainer.java
- dlink-core/src/main/java/com/dlink/explainer/ca/TableCA.java
- dlink-core/src/main/java/com/dlink/explainer/lineage/LineageBuilder.java
- dlink-core/src/main/java/com/dlink/plus/FlinkSqlPlus.java
- dlink-web/src/components/Studio/StudioConsole/StudioCA/index.tsx
- dlink-web/src/components/Studio/StudioEdit/data.d.ts
> Fixt to lineage

- dlink-doc/bin/auto.sh
> [Fix-220][docs] Fix to auto.sh

- dlink-doc/sql/dlink_history.sql
optimization dlink_history.sql file 
- *Comment the delete table statement in the file *
- *None*
> [Optimization-296][dlink-doc] optimization dlink_history.sql file 

- dlink-web/src/pages/AlertInstance/components/DingTalkForm.tsx
> [Fix-299] [web] Fix to DingTalk form does not display correctly

- dlink-admin/src/main/java/com/dlink/dto/StudioExecuteDTO.java
> [Fix-294] [admin] Fix to flink conf json bug

- docs/index.html
- docs/zh-CN/_sidebar.md
- docs/zh-CN/administrator-guide/Studio/job_dev/env_config.md
- docs/zh-CN/administrator-guide/Studio/job_dev/flinksql_guide/flinksql_job_dev.md
- docs/zh-CN/administrator-guide/Studio/job_dev/flinksql_guide/flinksql_job_submit.md
- docs/zh-CN/administrator-guide/Studio/job_dev/flinksql_guide/job_debug.md
- docs/zh-CN/administrator-guide/Studio/job_dev/flinksql_guide/summary.md
- docs/zh-CN/administrator-guide/Studio/job_dev/job_hosting.md
- docs/zh-CN/administrator-guide/Studio/job_ops/job_manage.md
Add flinksql Development Guide
add flinksql_guide
> [Document-332][docs] Add flinksql Development Guide

- docs/index.html
Add sidebar dinky logo
Modify index.html
> [Optimization-3443][doc] Add sidebar dinky logo

- dlink-alert/dlink-alert-feishu/src/main/java/com.dlink.alert.feishu/FeiShuSender.java
feishu alert when choose @all sendMsg failed 
- *update mkUserIds method*
This pull request is already covered by existing tests, such as **testTextTypeSend** , **testPostTypeSend**.
> [fix-350][alert] feishu alert when choose @all sendMsg failed bug

- dlink-admin/src/main/java/com/dlink/service/impl/TaskServiceImpl.java
> [Fix-358] [pom] Fix to  install

- docker-compose.yaml
- docker/mysql/Dockerfile
- docker/server/Dockerfile
- docker/web/Dockerfile
- docker/web/dinky.conf.template
增加docker支持
packge打包操作
```
docker-compose build
```
启动dinky服务
```
docker-compose up
```
启动了大概这样
访问 http://localhost:8080/ 即可
> add docker support

- dlink-metadata/dlink-metadata-hive/src/main/java/com/dlink/metadata/driver/HiveDriver.java
fix hive getSqlGeneration Exception
- change HiveDriver  the method  listTables to add **USE `DB`**
- None
> [fix-363][metadata-hive] fix hive getSqlGeneration Exception

- docs/zh-CN/FAQ.md
> [Document-365] [doc] add question

- dlink-metadata/dlink-metadata-hive/pom.xml
- dlink-web/src/pages/AlertInstance/components/EmailForm.tsx
- docs/zh-CN/_sidebar.md
- docs/zh-CN/deploy/build.md
- docs/zh-CN/deploy/deploy.md
- docs/zh-CN/developer_guide/remote_debug.md
- docs/zh-CN/extend/alert.md
- docs/zh-CN/extend/datasource.md
Optimization doc & metadata-hive pom
-  Optimization docs
- add alert, datasource  extend docs
-  add httpcore , httpclent to metadata-hive pom
- None
> [Optimization-371][metadata-hive,docs] Optimization doc & metadata-hive pom

- dlink-admin/pom.xml
- dlink-metadata/dlink-metadata-hive/pom.xml
add httpclient to admin jar
- * add httpclient to admin jar*
- None
> [Optimization-373][admin] add httpclient to admin jar

- dlink-admin/src/main/java/com/dlink/controller/StudioController.java
- dlink-admin/src/main/java/com/dlink/exception/WebExceptionHandler.java
- dlink-executor/src/test/java/com.dlink.executor/FlinkInterceptorTest.java
- dlink-web/src/components/Studio/StudioMenu/index.tsx
> [Fix-98][admin,web] Fix to show exception

- dlink-core/src/main/java/com/dlink/job/JobManager.java
- dlink-executor/src/main/java/com/dlink/executor/Executor.java
> [Fix-127][core,executor] Add executeAsync datastream job

- dlink-alert/dlink-alert-base/src/main/java/com/dlink/alert/Alert.java
- dlink-metadata/dlink-metadata-base/src/main/java/com/dlink/metadata/driver/Driver.java
> [Optimization-382][alert,metadata] Optimization SPI

- dlink-client/dlink-client-1.11/pom.xml
- dlink-client/dlink-client-1.11/src/main/java/com/dlink/cdc/FlinkCDCMergeBuilder.java
- dlink-client/dlink-client-1.12/pom.xml
- dlink-client/dlink-client-1.12/src/main/java/com/dlink/cdc/FlinkCDCMergeBuilder.java
- dlink-client/dlink-client-1.13/pom.xml
- dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/FlinkCDCMergeBuilder.java
- dlink-client/dlink-client-1.14/pom.xml
- dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/FlinkCDCMergeBuilder.java
> [Optimization-384][client] Optimization CDCSourceMerge

- dlink-daemon/src/main/java/com/dlink/daemon/task/DaemonTask.java
> [Optimization-397] [daemon] SPI Optimization

- dlink-admin/src/main/java/com/dlink/controller/ClusterConfigurationController.java
- dlink-admin/src/main/java/com/dlink/model/Cluster.java
- dlink-admin/src/main/java/com/dlink/model/ClusterConfiguration.java
- dlink-admin/src/main/java/com/dlink/model/DataBase.java
- dlink-admin/src/main/java/com/dlink/model/Task.java
- dlink-admin/src/main/java/com/dlink/model/User.java
- dlink-admin/src/main/java/com/dlink/service/impl/TaskServiceImpl.java
- dlink-admin/src/main/java/com/dlink/service/impl/UserServiceImpl.java
> [Fix-402] [admin] MybatisPlus PO boolean default false

- dlink-common/src/main/java/com/dlink/model/SystemConfiguration.java
> [Fix-405][common] Fix 修改系统配置的sql分隔符默认为 ;\r\n

- dlink-web/src/components/Common/JobStatus.tsx
- dlink-web/src/pages/Cluster/index.tsx
- dlink-web/src/pages/DevOps/JobInfo/index.tsx
FlinkWebUI button always exists, when job is running , finished , canceled and failed
FlinkWebUI button always exists, when job is running , finished , canceled and failed
- None
> [Optimization-406][web] FlinkWebUI button Optimization &&  add flinkwebui button for clusertInstance Manager

- dlink-admin/src/main/java/com/dlink/service/impl/TaskServiceImpl.java
> [Fix-427] [admin] Task status error when task has stoped

- dlink-admin/src/main/java/com/dlink/controller/CatalogueController.java
Code style Improve  about auto close File Resource.
> [Improve] Auto close File Resource

- dlink-client/dlink-client-1.11/src/main/java/com/dlink/cdc/SinkBuilderFactory.java
- dlink-client/dlink-client-1.11/src/main/java/com/dlink/cdc/doris/DorisSinkBuilder.java
- dlink-client/dlink-client-1.12/src/main/java/com/dlink/cdc/SinkBuilderFactory.java
- dlink-client/dlink-client-1.12/src/main/java/com/dlink/cdc/doris/DorisSinkBuilder.java
- dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/SinkBuilderFactory.java
- dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/doris/DorisSinkBuilder.java
- dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/SinkBuilderFactory.java
- dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/doris/DorisSinkBuilder.java
- dlink-executor/src/main/java/com/dlink/trans/ddl/CDCSource.java
- dlink-flink/dlink-flink-1.11/pom.xml
- dlink-flink/dlink-flink-1.12/pom.xml
- dlink-flink/dlink-flink-1.13/pom.xml
- dlink-flink/dlink-flink-1.14/pom.xml
> [Feature-435][client,executor] CDCSource sync doris

- dlink-client/dlink-client-1.11/src/main/java/com/dlink/cdc/AbstractCDCBuilder.java
- dlink-client/dlink-client-1.11/src/main/java/com/dlink/cdc/AbstractSinkBuilder.java
- dlink-client/dlink-client-1.11/src/main/java/com/dlink/cdc/doris/DorisSinkBuilder.java
- dlink-client/dlink-client-1.11/src/main/java/com/dlink/cdc/kafka/KafkaSinkBuilder.java
- dlink-client/dlink-client-1.12/src/main/java/com/dlink/cdc/AbstractCDCBuilder.java
- dlink-client/dlink-client-1.12/src/main/java/com/dlink/cdc/AbstractSinkBuilder.java
- dlink-client/dlink-client-1.12/src/main/java/com/dlink/cdc/doris/DorisSinkBuilder.java
- dlink-client/dlink-client-1.12/src/main/java/com/dlink/cdc/kafka/KafkaSinkBuilder.java
- dlink-client/dlink-client-1.13/pom.xml
- dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/AbstractCDCBuilder.java
- dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/AbstractSinkBuilder.java
- dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/doris/DorisSinkBuilder.java
- dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/jdbc/JdbcSinkBuilder.java
- dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/kafka/KafkaSinkBuilder.java
- dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/AbstractCDCBuilder.java
- dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/AbstractSinkBuilder.java
- dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/doris/DorisSinkBuilder.java
- dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/jdbc/JdbcSinkBuilder.java
- dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/kafka/KafkaSinkBuilder.java
> [Optimization-439][client] Optimize CDCSource sync doris

- dlink-web/src/components/Studio/StudioLeftTool/StudioMetaData/index.tsx
fix metadata switching error
- *fix metadata switching error*
数据开发  ->  左侧 `元数据管理` -> 选择任意表 右键查看表信息   -> 点击关闭  -> 切换其他数据源 -> 选择任意表 查看表信息
> [Fix-387][web] metadata switching error

- dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/AbstractSinkBuilder.java
- dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/SinkBuilderFactory.java
- dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/doris/DorisSinkBuilder.java
- dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/hudi/HudiSinkBuilder.java
- dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/jdbc/JdbcSinkBuilder.java
- dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/kafka/KafkaSinkBuilder.java
- dlink-common/src/main/java/com/dlink/model/Table.java
- dlink-flink/dlink-flink-1.13/pom.xml
> [Feature-442][client,executor] CDCSource sync hudi

- dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/hudi/HudiSinkBuilder.java
> [Fix-442][client,executor] Add SOURCE_AVRO_SCHEMA

- dlink-client/dlink-client-1.11/src/main/java/com/dlink/cdc/AbstractSinkBuilder.java
- dlink-client/dlink-client-1.11/src/main/java/com/dlink/cdc/doris/DorisSinkBuilder.java
- dlink-client/dlink-client-1.11/src/main/java/com/dlink/cdc/kafka/KafkaSinkBuilder.java
- dlink-client/dlink-client-1.12/src/main/java/com/dlink/cdc/AbstractSinkBuilder.java
- dlink-client/dlink-client-1.12/src/main/java/com/dlink/cdc/doris/DorisSinkBuilder.java
- dlink-client/dlink-client-1.12/src/main/java/com/dlink/cdc/kafka/KafkaSinkBuilder.java
- dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/AbstractSinkBuilder.java
- dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/doris/DorisSinkBuilder.java
- dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/hudi/HudiSinkBuilder.java
- dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/kafka/KafkaSinkBuilder.java
- dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/AbstractSinkBuilder.java
- dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/doris/DorisSinkBuilder.java
- dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/jdbc/JdbcSinkBuilder.java
- dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/kafka/KafkaSinkBuilder.java
> [Feature-445][client] CDCSource sync add sink table-name rule

- dlink-metadata/dlink-metadata-doris/src/test/java/com/dlink/metadata/DorisTest.java
- dlink-metadata/dlink-metadata-mysql/src/test/java/com/dlink/metadata/MysqlTest.java
- dlink-metadata/dlink-metadata-oracle/src/test/java/com/dlink/metadata/OracleTest.java
- dlink-metadata/dlink-metadata-sqlserver/src/test/java/com/dlink/metadata/SqlServerTest.java
Resolve connection failure null pointer problem
> Assign to DriverConfig's name

- dlink-admin/src/main/java/com/dlink/model/AlertInstance.java
- dlink-alert/dlink-alert-wechat/src/main/java/com/dlink/alert/wechat/WeChatSender.java
- dlink-web/src/pages/AlertInstance/components/WeChatForm.tsx
Optimization wechat Webhook sendMsg title 
- *修改企微webhook发送类型的title*
- *删除前端企微-APP类型表单的`发送信息`项*
- None
> [Optimization-459][alert-wechat,web] Optimization wechat Webhook sendMsg title 

- dlink-client/dlink-client-1.11/src/main/java/com/dlink/cdc/AbstractCDCBuilder.java
- dlink-client/dlink-client-1.11/src/main/java/com/dlink/cdc/AbstractSinkBuilder.java
- dlink-client/dlink-client-1.11/src/main/java/com/dlink/cdc/mysql/MysqlCDCBuilder.java
- dlink-client/dlink-client-1.11/src/main/java/com/dlink/cdc/sql/SQLSinkBuilder.java
- dlink-client/dlink-client-1.12/src/main/java/com/dlink/cdc/AbstractCDCBuilder.java
- dlink-client/dlink-client-1.12/src/main/java/com/dlink/cdc/AbstractSinkBuilder.java
- dlink-client/dlink-client-1.12/src/main/java/com/dlink/cdc/mysql/MysqlCDCBuilder.java
- dlink-client/dlink-client-1.12/src/main/java/com/dlink/cdc/sql/SQLSinkBuilder.java
- dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/AbstractCDCBuilder.java
- dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/AbstractSinkBuilder.java
- dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/hudi/HudiSinkBuilder.java
- dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/mysql/MysqlCDCBuilder.java
- dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/oracle/OracleCDCBuilder.java
- dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/sql/SQLSinkBuilder.java
- dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/AbstractCDCBuilder.java
- dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/AbstractSinkBuilder.java
- dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/mysql/MysqlCDCBuilder.java
- dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/oracle/OracleCDCBuilder.java
- dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/sql/SQLSinkBuilder.java
- dlink-client/dlink-client-base/src/main/java/com/dlink/model/FlinkCDCConfig.java
- dlink-common/src/main/java/com/dlink/model/ColumnType.java
- dlink-executor/src/main/java/com/dlink/trans/ddl/CDCSource.java
- dlink-executor/src/main/java/com/dlink/trans/ddl/CreateCDCSourceOperation.java
> [Feature-461][client] CDCSource sync add sink table-name RegExp

- dlink-web/src/components/Studio/StudioRightTool/StudioJarSetting/index.tsx
- dlink-web/src/components/Studio/StudioRightTool/StudioSetting/index.tsx
> [Fix-457][web]Fix bug of modifying job name

- dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/mysql/MysqlCDCBuilder.java
- dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/mysql/MysqlCDCBuilder.java
- dlink-client/dlink-client-base/src/main/java/com/dlink/model/FlinkCDCConfig.java
- dlink-executor/src/main/java/com/dlink/trans/ddl/CDCSource.java
- dlink-executor/src/main/java/com/dlink/trans/ddl/CreateCDCSourceOperation.java
> [Feature-469][client] Add MysqlCDCSource sync extended configuration

- README.en-US.md
- README.md
- README.zh-CN.md
- docs/en-US/_navbar.md
- docs/zh-CN/deploy/build.md
- docs/zh-CN/developer_guide/how_contribute.md
- docs/zh-CN/developer_guide/remote_debug.md
- docs/zh-CN/quick_start/build.md
- Fix some inaccessible documentation links.
- Fix some inaccessible documentation links.
- This change is a trivial rework / code cleanup without any test coverage.
> [Fix-479][docs] Fix some inaccessible documentation links.

- dlink-admin/src/main/java/com/dlink/controller/StudioController.java
- dlink-core/src/main/java/com/dlink/explainer/Explainer.java
- dlink-core/src/main/java/com/dlink/job/JobParam.java
> [Fix-484] [core] Fix to job plan info was executed twice

- dlink-admin/src/main/java/com/dlink/model/JobInstance.java
[Fix-491][admin,web] Fix refresh the status page with abnormal jitter
Fix bug refresh the status page with abnormal jitter #491 
dlink-admin/src/main/java/com/dlink/model/JobInstance.java add @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss")
no
no
(or)
> [Fix-491][admin,web] Fix refresh the status page with abnormal jitter

- dlink-client/dlink-client-1.13/src/main/java/com/dlink/executor/CustomTableEnvironmentImpl.java
- dlink-client/dlink-client-1.14/src/main/java/com/dlink/executor/CustomTableEnvironmentImpl.java
- dlink-executor/src/main/java/com/dlink/interceptor/FlinkInterceptor.java
> [Fix-503][client] Remove initFunctions

- dlink-assembly/src/main/assembly/package.xml
- dlink-client/dlink-client-1.11/src/main/java/com/dlink/cdc/AbstractSinkBuilder.java
- dlink-client/dlink-client-1.11/src/main/java/com/dlink/cdc/sql/SQLSinkBuilder.java
- dlink-client/dlink-client-1.12/src/main/java/com/dlink/cdc/AbstractSinkBuilder.java
- dlink-client/dlink-client-1.12/src/main/java/com/dlink/cdc/sql/SQLSinkBuilder.java
- dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/AbstractSinkBuilder.java
- dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/sql/SQLSinkBuilder.java
- dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/AbstractSinkBuilder.java
- dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/sql/SQLSinkBuilder.java
- dlink-client/dlink-client-1.15/src/main/java/com/dlink/cdc/AbstractSinkBuilder.java
- dlink-client/dlink-client-1.15/src/main/java/com/dlink/cdc/sql/SQLSinkBuilder.java
- dlink-client/dlink-client-base/src/main/java/com/dlink/model/FlinkCDCConfig.java
- dlink-common/src/main/java/com/dlink/model/ColumnType.java
- dlink-core/src/test/java/com/dlink/core/BatchTest.java
- dlink-executor/src/main/java/com/dlink/trans/AbstractOperation.java
- dlink-executor/src/main/java/com/dlink/trans/ddl/CreateCDCSourceOperation.java
> [Feature-518][client] CDCSOURCE add log and fix decimal bug

- dlink-core/src/main/java/com/dlink/explainer/Explainer.java
- dlink-core/src/main/java/com/dlink/job/JobParam.java
> [Fix-520] [core] Fix get JobPlanInfo failed

- dlink-client/dlink-client-1.11/src/main/java/com/dlink/cdc/sql/SQLSinkBuilder.java
- dlink-client/dlink-client-1.12/src/main/java/com/dlink/cdc/sql/SQLSinkBuilder.java
- dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/sql/SQLSinkBuilder.java
- dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/sql/SQLSinkBuilder.java
- dlink-client/dlink-client-1.15/src/main/java/com/dlink/cdc/sql/SQLSinkBuilder.java
- dlink-metadata/dlink-metadata-oracle/src/main/java/com/dlink/metadata/convert/OracleTypeConvert.java
> [Fix-522] [client] Fix CDCSOURCE OracleCDC number can't be cast to Long

- dlink-alert/dlink-alert-dingtalk/src/main/java/com/dlink/alert/dingtalk/DingTalkSender.java
- dlink-web/src/pages/AlertInstance/components/DingTalkForm.tsx
Add @mobile mode of dingTalk Alert
Add @mobile mode of dingTalk Alert
> [Feature-525][dlink-alert-dingtalk,web] Add @mobile mode of dingTalk Alert

- dlink-alert/dlink-alert-feishu/src/main/java/com.dlink.alert.feishu/FeiShuConstants.java
- dlink-alert/dlink-alert-feishu/src/main/java/com.dlink.alert.feishu/FeiShuSender.java
- dlink-alert/dlink-alert-wechat/src/main/java/com/dlink/alert/wechat/WeChatSender.java
- dlink-web/src/pages/AlertInstance/components/WeChatForm.tsx
fix the wechat alarm instance send testMsg error
fix the wechat alarm instance send testMsg error
> [Fix-527][web] the wechat alarm instance send testMsg error

- dlink-web/src/pages/DataStudio/model.ts
> [Fix-529] [web] Fix the task cannot be saved after switching tasks

- dlink-web/src/components/Studio/StudioConsole/StudioCA/index.tsx
> [Feature-254][web] Add StreamGraph JSON Export function

- dlink-admin/src/main/java/com/dlink/controller/APIController.java
- dlink-admin/src/main/java/com/dlink/controller/TaskController.java
- dlink-admin/src/main/java/com/dlink/service/TaskService.java
- dlink-admin/src/main/java/com/dlink/service/impl/TaskServiceImpl.java
- dlink-web/src/components/Studio/StudioMenu/index.tsx
- dlink-web/src/pages/API/TaskAPI/index.tsx
- dlink-web/src/pages/API/service.ts
> [Feature-534][admin,web] Add task open API page

- dlink-web/src/components/Studio/StudioMenu/StudioHelp/index.tsx
> [Feature-356][web] Add datastudio help page

- dlink-admin/src/main/java/com/dlink/controller/StudioController.java
- dlink-admin/src/main/java/com/dlink/dto/StudioCADTO.java
- dlink-admin/src/main/java/com/dlink/service/impl/StudioServiceImpl.java
- dlink-core/pom.xml
- dlink-core/src/main/java/com/dlink/explainer/sqlLineage/LineageBuilder.java
- dlink-core/src/main/java/com/dlink/explainer/sqlLineage/LineageColumn.java
- dlink-core/src/main/java/com/dlink/explainer/sqlLineage/LineageUtils.java
- dlink-core/src/main/java/com/dlink/explainer/sqlLineage/TreeNode.java
- dlink-core/src/main/java/com/dlink/explainer/sqlLineage/TreeNodeIterator.java
- dlink-web/src/components/Lineage/index.tsx
- dlink-web/src/components/Studio/StudioConsole/StudioCA/index.tsx
- dlink-web/src/components/Studio/StudioEdit/data.d.ts
Add column lineage from db sql
> [Feature-318][core] Add column lineage from db sql

- dlink-web/src/components/Studio/StudioLeftTool/StudioDataBase/index.tsx
- dlink-web/src/components/Studio/StudioLeftTool/StudioMetaData/index.tsx
修复 注册的数据源“别名”为空时，单击数据开发>元数据>选择数据源时只显示数据源类型，不显示名称
修复 注册的数据源“别名”为空时，单击数据开发>元数据>选择数据源时只显示数据源类型，不显示名称
metadata page 单击 数据开发>元数据>选择数据源
datasource  page 单击 数据开发>数据源
> [Fix-541]  Fix the problem that the datasource && metadata does not set alias 

- dlink-admin/src/main/java/com/dlink/controller/JobInstanceController.java
- dlink-admin/src/main/java/com/dlink/job/FlinkJobTask.java
- dlink-admin/src/main/java/com/dlink/job/FlinkJobTaskPool.java
- dlink-admin/src/main/java/com/dlink/model/JobInfoDetail.java
- dlink-admin/src/main/java/com/dlink/service/JobHistoryService.java
- dlink-admin/src/main/java/com/dlink/service/JobInstanceService.java
- dlink-admin/src/main/java/com/dlink/service/impl/JobHistoryServiceImpl.java
- dlink-admin/src/main/java/com/dlink/service/impl/JobInstanceServiceImpl.java
- dlink-admin/src/main/java/com/dlink/service/impl/TaskServiceImpl.java
- dlink-common/src/main/java/com/dlink/pool/AbstractPool.java
> [Feature-545][admin] Add Task Pool to solve frequent database writes

- dlink-admin/src/main/java/com/dlink/service/impl/ClusterConfigurationServiceImpl.java
- dlink-gateway/src/main/java/com/dlink/gateway/config/ClusterConfig.java
- dlink-gateway/src/main/java/com/dlink/gateway/kubernetes/KubernetesGateway.java
> [Fix-556][adimin,gateway] Fix flinkLibPath in K8S configuration is null

- dlink-web/package.json
> [Optimization-562][web] Remove preset-ui

- dlink-metadata/dlink-metadata-mysql/src/main/java/com/dlink/metadata/convert/MySqlTypeConvert.java
> [Optimization-564][metadata] Optimization MySqlTypeConvert

- dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/mysql/MysqlCDCBuilder.java
- dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/mysql/MysqlCDCBuilder.java
- dlink-client/dlink-client-1.15/src/main/java/com/dlink/cdc/mysql/MysqlCDCBuilder.java
- dlink-client/dlink-client-base/src/main/java/com/dlink/model/FlinkCDCConfig.java
- dlink-executor/src/main/java/com/dlink/trans/ddl/CDCSource.java
- dlink-executor/src/main/java/com/dlink/trans/ddl/CreateCDCSourceOperation.java
- dlink-flink/dlink-flink-1.13/pom.xml
- dlink-flink/dlink-flink-1.14/pom.xml
> 为mysql source cdc添加jdbc连接参数；升级1.13和1.14 cdc连接版本（2.2.0->2.2.1）

- dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/sql/SQLSinkBuilder.java
- dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/sql/SQLSinkBuilder.java
- dlink-client/dlink-client-1.15/src/main/java/com/dlink/cdc/sql/SQLSinkBuilder.java
> [Fix-571] [client] Fix CDCSOURCE String can't be cast to Timestamp

- dlink-web/src/components/Studio/StudioRightTool/StudioSqlConfig/index.tsx
fix datastudio select datasource alias is ""
> [Fix-577][web]fix datastudio select datasource alias is ""

- dlink-admin/src/main/java/com/dlink/service/impl/DataBaseServiceImpl.java
fix Got "Something went wrong." page after right clicking another table on Metadata tab panel when you have operated the selected table
*(or)*
(or)
> [fix-576][admin] Fix the exception caused by metadata switching

- dlink-admin/src/main/java/com/dlink/model/Task.java
- dlink-admin/src/main/java/com/dlink/service/impl/TaskServiceImpl.java
Fix NPE on running yarn per-job app
> [Fix-596][admin] Fix NPE on running yarn per-job app

- dlink-web/src/components/Studio/StudioConsole/StudioProcess/index.tsx
- dlink-web/src/components/Studio/StudioLeftTool/StudioConnector/components/SessionForm.tsx
- dlink-web/src/components/Studio/StudioRightTool/StudioJarSetting/index.tsx
- dlink-web/src/components/Studio/StudioRightTool/StudioSetting/index.tsx
- dlink-web/src/pages/ClusterConfiguration/components/ClusterConfigurationForm.tsx
> [Optimization-605][web] fix The alias is empty in several places

- dlink-core/src/main/java/com/dlink/job/JobManager.java
- dlink-core/src/main/java/com/dlink/result/ResultBuilder.java
- dlink-core/src/main/java/com/dlink/result/ResultRunnable.java
- dlink-core/src/main/java/com/dlink/result/SelectResultBuilder.java
- dlink-executor/src/main/java/com/dlink/executor/Executor.java
> [Fix-140][core] Fix 'table.local-time-zone' parameter is invalid

- dlink-core/src/main/java/com/dlink/explainer/Explainer.java
> [Fix-621] [core] Fix can't explain 'show datatbases'

- dlink-core/src/main/java/com/dlink/explainer/trans/TransGenerator.java
> [Fix][core]: setParentId() 方法判空错误

- dlink-core/src/main/java/com/dlink/explainer/lineage/LineageTable.java
- dlink-web/src/components/Lineage/index.tsx
- dlink-web/src/components/Studio/StudioConsole/StudioCA/index.tsx
- dlink-web/src/pages/DevOps/JobInfo/DataMap/index.tsx
> [Optimization-633][web] Optimization lineage refresh

- dlink-admin/src/main/java/com/dlink/controller/APIController.java
- dlink-web/src/pages/API/TaskAPI/index.tsx
> [Feature-635][admin] Add job instance info api

- dlink-admin/src/main/java/com/dlink/service/impl/AlertInstanceServiceImpl.java
- dlink-admin/src/main/java/com/dlink/service/impl/TaskServiceImpl.java
- dlink-alert/dlink-alert-base/src/main/java/com/dlink/alert/AlertMsg.java
- dlink-alert/dlink-alert-dingtalk/src/test/java/com/dlink/alert/dingtalk/DingTalkTest.java
- dlink-alert/dlink-alert-email/src/test/java/com/dlink/alert/email/EmailSenderTest.java
- dlink-alert/dlink-alert-feishu/src/main/java/com.dlink.alert.feishu/FeiShuSender.java
- dlink-alert/dlink-alert-feishu/src/test/java/com.dlink.alert.feishu/FeiShuSenderTest.java
- dlink-alert/dlink-alert-wechat/src/main/java/com/dlink/alert/wechat/WeChatConstants.java
- dlink-alert/dlink-alert-wechat/src/main/java/com/dlink/alert/wechat/WeChatSender.java
- dlink-core/src/main/java/com/dlink/api/FlinkAPI.java
- dlink-core/src/main/java/com/dlink/constant/FlinkRestAPIConstant.java
- dlink-core/src/test/java/com/dlink/core/FlinkRestAPITest.java
- dlink-web/src/pages/AlertInstance/components/WeChatForm.tsx
- dlink-web/src/pages/Cluster/index.tsx
Optimization all Alert of sendMsg
*(or)*
(or)
> [Optimization-640][Alert,web] Optimization all Alert of sendMsg 

- dlink-admin/src/main/java/com/dlink/model/JobInfoDetail.java
- dlink-admin/src/main/java/com/dlink/model/JobManagerConfiguration.java
- dlink-admin/src/main/java/com/dlink/service/impl/TaskServiceImpl.java
- dlink-web/src/pages/DevOps/JobInfo/CheckPoints/index.tsx
- dlink-web/src/pages/DevOps/JobInfo/ClusterConfiguration/index.tsx
- dlink-web/src/pages/DevOps/JobInfo/Config/index.tsx
- dlink-web/src/pages/DevOps/JobInfo/index.tsx
- dlink-web/src/pages/DevOps/data.d.ts
…f DevOps
1. add snapshotinfo
2. add taskmanagerConfig
3. update configInfo 
> [Feature-644][admin,web] add snapshotinfo ,taskmanagerConfig && update configInfo of DevOps 

- dlink-alert/dlink-alert-email/src/main/java/com/dlink/alert/email/MailSender.java
[Fix-638][Alert]Fix problems about the email alarm notification, cannot customize the nickname.
[Fix-638][Alert]Fix problems about the email alarm notification, cannot customize the nickname.
> [Fix-638][Alert]Fix problems about the email alarm notification, cannot customize the nickname.

- dlink-admin/src/main/java/com/dlink/model/JobInfoDetail.java
- dlink-admin/src/main/java/com/dlink/model/TaskContainerConfigInfo.java
- dlink-admin/src/main/java/com/dlink/model/TaskManagerConfiguration.java
- dlink-admin/src/main/java/com/dlink/service/impl/TaskServiceImpl.java
- dlink-web/src/global.less
- dlink-web/src/pages/DevOps/JobInfo/ClusterConfiguration/JobManager/index.tsx
- dlink-web/src/pages/DevOps/JobInfo/ClusterConfiguration/TaskManager/index.tsx
- dlink-web/src/pages/DevOps/JobInfo/ClusterConfiguration/index.tsx
- dlink-web/src/pages/DevOps/data.d.ts
add taskManager tableForm of DevOps
>  [Feature-649][admin,web] add taskManager tableForm of DevOps

- dlink-web/src/components/Studio/StudioRightTool/StudioTaskInfo/index.less
- dlink-web/src/components/Studio/StudioRightTool/StudioTaskInfo/index.tsx
- dlink-web/src/components/Studio/StudioRightTool/index.tsx
> [Feature-654][web] Add task info tab

- dlink-admin/src/main/java/com/dlink/job/BuildConfiguration.java
- dlink-admin/src/main/java/com/dlink/service/impl/JobInstanceServiceImpl.java
- dlink-admin/src/main/java/com/dlink/service/impl/TaskServiceImpl.java
- dlink-web/src/pages/DevOps/JobInfo/ClusterConfiguration/JobManager/index.tsx
- dlink-web/src/pages/DevOps/JobInfo/ClusterConfiguration/TaskManager/index.tsx
- dlink-web/src/pages/DevOps/JobInfo/ClusterConfiguration/index.tsx
> [Feature-649][admin,web] update taskManager tableForm of DevOps

- dlink-admin/src/main/java/com/dlink/controller/TaskController.java
- dlink-admin/src/main/java/com/dlink/controller/TaskVersionController.java
- dlink-admin/src/main/java/com/dlink/dto/TaskRollbackVersionDTO.java
- dlink-admin/src/main/java/com/dlink/dto/TaskVersionConfigureDTO.java
- dlink-admin/src/main/java/com/dlink/dto/TaskVersionHistoryDTO.java
- dlink-admin/src/main/java/com/dlink/mapper/TaskVersionMapper.java
- dlink-admin/src/main/java/com/dlink/model/Task.java
- dlink-admin/src/main/java/com/dlink/model/TaskVersion.java
- dlink-admin/src/main/java/com/dlink/service/TaskService.java
- dlink-admin/src/main/java/com/dlink/service/TaskVersionService.java
- dlink-admin/src/main/java/com/dlink/service/impl/TaskServiceImpl.java
- dlink-admin/src/main/java/com/dlink/service/impl/TaskVersionServiceImpl.java
- dlink-admin/src/main/resources/mapper/TaskVersionMapper.xml
- dlink-doc/sql/dlink.sql
- dlink-doc/sql/dlink_history.sql
- dlink-web/src/components/Studio/StudioRightTool/StudioHistory/data.d.ts
- dlink-web/src/components/Studio/StudioRightTool/StudioHistory/index.tsx
- dlink-web/src/components/Studio/StudioRightTool/index.tsx
Purpose of the pull request
This pull request adds flink sql history verison
Brief change log
Add DDL change to dlink_doc/dlink_history.sql
Add java code to dlink-admin module
Verify this pull request
> [feature][admin,web] add task version history

- dlink-web/src/components/Common/function.ts
- dlink-web/src/pages/DevOps/JobInfo/CheckPoints/index.tsx
- dlink-web/src/pages/DevOps/data.d.ts
> [Feature-661][web] add job CheckPoint History 

- dlink-admin/src/main/java/com/dlink/controller/CatalogueController.java
- dlink-admin/src/main/java/com/dlink/mapper/TaskMapper.java
- dlink-admin/src/main/java/com/dlink/service/CatalogueService.java
- dlink-admin/src/main/java/com/dlink/service/TaskService.java
- dlink-admin/src/main/java/com/dlink/service/impl/CatalogueServiceImpl.java
- dlink-admin/src/main/java/com/dlink/service/impl/TaskServiceImpl.java
- dlink-admin/src/main/resources/mapper/TaskMapper.xml
- dlink-web/src/components/Studio/StudioTree/index.tsx
> [feature][admin,web]add  task copy feature

- dlink-client/dlink-client-1.11/src/main/java/com/dlink/cdc/AbstractSinkBuilder.java
- dlink-client/dlink-client-1.11/src/main/java/com/dlink/cdc/sql/SQLSinkBuilder.java
- dlink-client/dlink-client-1.12/src/main/java/com/dlink/cdc/AbstractSinkBuilder.java
- dlink-client/dlink-client-1.12/src/main/java/com/dlink/cdc/sql/SQLSinkBuilder.java
- dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/AbstractSinkBuilder.java
- dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/sql/SQLSinkBuilder.java
- dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/AbstractSinkBuilder.java
- dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/sql/SQLSinkBuilder.java
- dlink-client/dlink-client-1.15/src/main/java/com/dlink/cdc/AbstractSinkBuilder.java
- dlink-client/dlink-client-1.15/src/main/java/com/dlink/cdc/sql/SQLSinkBuilder.java
fix #674 
- Modify AbstractSinkBuilder.java
- Modify SQLSinkBuilder.java
> [fix-674] Support MySQL varbinary and binary in CDCSOURCE.

- dlink-admin/src/main/java/com/dlink/controller/TaskVersionController.java
- dlink-admin/src/main/java/com/dlink/dto/TaskVersionHistoryDTO.java
- dlink-web/src/pages/DevOps/JobInfo/Version/index.tsx
- dlink-web/src/pages/DevOps/JobInfo/index.tsx
- dlink-web/src/pages/DevOps/data.d.ts
Feature [#685](https://github.com/DataLinkDC/dlink/issues/685)
点击 **查看作业详情** 即能查看当前版本的执行SQL
> [Feature-685][web,admin] add job historyversion list of DevOps

- dlink-admin/src/main/java/com/dlink/service/impl/UserServiceImpl.java
> [Optimization-713][dlink-admin]修复已被删除的用户登录，显示信息不正确问题。

- dlink-connectors/dlink-connector-doris-1.13/pom.xml
- dlink-connectors/dlink-connector-doris-1.13/src/main/java/org/apache/doris/flink/serialization/RowBatch.java
- dlink-connectors/pom.xml
> 1.13版本Doris连接，作为来源隐藏会收集到隐藏位置“__DORIS_DELETE_”，读取数据会报错

- dlink-web/src/components/Studio/StudioRightTool/StudioHistory/index.tsx
- dlink-web/src/pages/DevOps/JobInfo/CheckPoints/index.tsx
- dlink-web/src/pages/DevOps/JobInfo/Config/index.tsx
- dlink-web/src/pages/DevOps/data.d.ts
fix #719 checkpoint has error of devops && add savepoints info
- fix checkpoint has error
- add savepoints info
在dinky 触发savepoint时 会产生记录
eg:
> [fix-719][web] fix checkpoint has error of devops && add savepoints info

- dlink-admin/src/main/java/com/dlink/controller/StudioController.java
- dlink-admin/src/main/java/com/dlink/dto/StudioMetaStoreDTO.java
- dlink-admin/src/main/java/com/dlink/service/StudioService.java
- dlink-admin/src/main/java/com/dlink/service/impl/StudioServiceImpl.java
- dlink-admin/src/main/java/com/dlink/service/impl/TaskServiceImpl.java
- dlink-common/src/main/java/com/dlink/model/Catalog.java
- dlink-core/src/main/java/com/dlink/job/JobManager.java
- dlink-web/src/components/Studio/StudioEdit/data.d.ts
- dlink-web/src/components/Studio/StudioEvent/DDL.ts
- dlink-web/src/components/Studio/StudioLeftTool/StudioMetaStore/index.tsx
- dlink-web/src/components/Studio/StudioLeftTool/index.tsx
- dlink-web/src/components/Studio/StudioMenu/index.tsx
- dlink-web/src/components/Studio/StudioTree/index.tsx
- dlink-web/src/components/Studio/index.tsx
- dlink-web/src/pages/DataStudio/model.ts
- dlink-web/src/pages/DataStudio/service.ts
> [Feature-728][admin,web] Add meta store feature

- dlink-web/src/pages/DevOps/JobInfo/CheckPoints/index.tsx
- dlink-web/src/pages/DevOps/data.d.ts
optimization #719
更优雅的解析json数据
*(or)*
(or)
> [optimization-#719][web]optimization checkpoints page

- dlink-admin/src/main/java/com/dlink/utils/CopyrightUtil.java
> [fix-738][admin] fix  CopyrightUtil

- dlink-app/dlink-app-base/src/main/java/com/dlink/app/flinksql/Submiter.java
> [fix-741][dlink-app]fix application mode submit failed

- dlink-admin/src/main/java/com/dlink/controller/TaskController.java
- dlink-admin/src/main/java/com/dlink/model/Catalogue.java
- dlink-admin/src/main/java/com/dlink/model/Task.java
- dlink-admin/src/main/java/com/dlink/service/CatalogueService.java
- dlink-admin/src/main/java/com/dlink/service/TaskService.java
- dlink-admin/src/main/java/com/dlink/service/impl/CatalogueServiceImpl.java
- dlink-admin/src/main/java/com/dlink/service/impl/TaskServiceImpl.java
- dlink-web/src/components/Common/crud.ts
- dlink-web/src/components/Studio/StudioTree/index.tsx
> [Feature-750][admin,web] Add import and export tasks json

- dlink-admin/src/main/java/com/dlink/service/impl/AlertInstanceServiceImpl.java
- dlink-admin/src/main/resources/application.yml
> Pr allow circular references config add

- dlink-admin/src/main/java/com/dlink/service/impl/CatalogueServiceImpl.java
fix #750
Delete unreferenced classes
*(or)*
(or)
> [fix-750][admin]Delete unreferenced classes

- dlink-admin/src/main/java/com/dlink/service/impl/TaskServiceImpl.java
> [Feature] [dlink-admin] 修改重复判断的问题

- docs/docs/data_integration_guide/cdcsource_statements.md
- docs/versioned_docs/version-0.6/data_integration_guide/cdcsource_statements.md
> [fix-769][docs] fix The whole library synchronization document repair

- docs/docs/administrator_guide/studio/job_import_export.md
- docs/versioned_docs/version-0.6/administrator_guide/studio/job_import_export.md
add import and export job
add job_import_export.md
*(or)*
(or)
> [Feature][docs] Add import and export job docs

- dlink-admin/src/main/java/com/dlink/service/impl/CatalogueServiceImpl.java
> [Optimization-780][admin] Optimization The task version was not deleted after deleting the task

- dlink-web/src/components/Studio/StudioTree/index.tsx
> [Optimization-781][web] Optimization Overflow in job list tree after importing file 

- dlink-web/src/components/Studio/StudioConsole/StudioHistory/index.tsx
Optimization #801 
*(or)*
(or)
> [Optimization-801][web]Optimization StudioConsole's StudioProcess 

- dlink-web/src/pages/ResourceCenter/NamespaceManager/components/NameSpaceForm.tsx
- dlink-web/src/pages/ResourceCenter/UserManager/components/PasswordForm.tsx
> added NameSpaceForm PasswordForm

- .gitignore
> Added ignore of logs folder in git ignore file.

- dlink-admin/src/main/java/com/dlink/model/JobHistory.java
- dlink-admin/src/main/java/com/dlink/service/impl/JobHistoryServiceImpl.java
- dlink-admin/src/main/java/com/dlink/service/impl/TaskServiceImpl.java
> Fix jobhistory bug

- dlink-client/dlink-client-1.11/src/main/java/com/dlink/cdc/AbstractSinkBuilder.java
- dlink-client/dlink-client-1.11/src/main/java/com/dlink/cdc/kafka/KafkaSinkBuilder.java
- dlink-client/dlink-client-1.11/src/main/java/com/dlink/cdc/sql/SQLSinkBuilder.java
- dlink-client/dlink-client-1.12/src/main/java/com/dlink/cdc/AbstractSinkBuilder.java
- dlink-client/dlink-client-1.12/src/main/java/com/dlink/cdc/kafka/KafkaSinkBuilder.java
- dlink-client/dlink-client-1.12/src/main/java/com/dlink/cdc/sql/SQLSinkBuilder.java
- dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/AbstractSinkBuilder.java
- dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/kafka/KafkaSinkBuilder.java
- dlink-client/dlink-client-1.13/src/main/java/com/dlink/cdc/sql/SQLSinkBuilder.java
- dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/AbstractSinkBuilder.java
- dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/kafka/KafkaSinkBuilder.java
- dlink-client/dlink-client-1.14/src/main/java/com/dlink/cdc/sql/SQLSinkBuilder.java
- dlink-client/dlink-client-1.15/src/main/java/com/dlink/cdc/AbstractSinkBuilder.java
- dlink-client/dlink-client-1.15/src/main/java/com/dlink/cdc/kafka/KafkaSinkBuilder.java
- dlink-client/dlink-client-1.15/src/main/java/com/dlink/cdc/sql/SQLSinkBuilder.java
Optmizatiion cdcsource filter to process https://github.com/DataLinkDC/dlink/issues/773
change cdcsource filter to process
[dlink-client]kafkaSinkBuilder and SQLSinkBuilder
> 优化 cdc SQLSinkBuilder KafkaSinkBuilder, filter to process
